#!/bin/bash
echo PATH="/usr/local/bin:/usr/bin:/bin"

mount | grep sda2 || mount /dev/sda2 /media/ || exit 1
mount | grep sda1 || mount /dev/sda1 /media/boot/ || exit 1

touch /media/boot/ssh

if [ ! -f /media/boot/config.txt.dist ]; then
  cp /media/boot/config.txt /media/boot/config.txt.dist
fi

cat<<EOF > /media/boot/config.txt
# For more options and information see
# http://rpf.io/configtxt
# Some settings may impact device functionality. See link above for details

# uncomment if you get no picture on HDMI for a default "safe" mode
#hdmi_safe=1

# uncomment this if your display has a black border of unused pixels visible
# and your display can output without overscan
#disable_overscan=1

# uncomment the following to adjust overscan. Use positive numbers if console
# goes off screen, and negative if there is too much border
#overscan_left=16
#overscan_right=16
#overscan_top=16
#overscan_bottom=16

# uncomment to force a console size. By default it will be display's size minus
# overscan.
#framebuffer_width=1280
#framebuffer_height=720

# uncomment if hdmi display is not detected and composite is being output
#hdmi_force_hotplug=1

# uncomment to force a specific HDMI mode (this will force VGA)
#hdmi_group=1
#hdmi_mode=1

# uncomment to force a HDMI mode rather than DVI. This can make audio work in
# DMT (computer monitor) modes
#hdmi_drive=2

# uncomment to increase signal to HDMI, if you have interference, blanking, or
# no display
#config_hdmi_boost=4

# uncomment for composite PAL
#sdtv_mode=2

#uncomment to overclock the arm. 700 MHz is the default.
#arm_freq=800

# Uncomment some or all of these to enable the optional hardware interfaces
#dtparam=i2c_arm=on
#dtparam=i2s=on
#dtparam=spi=on

# Uncomment this to enable the lirc-rpi module
#dtoverlay=lirc-rpi

# Additional overlays and parameters are documented /boot/overlays/README

# Enable audio (loads snd_bcm2835)
dtparam=audio=on
EOF

cat<<EOF > /media/boot/wpa_supplicant.conf
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1

network={
        ssid="GitHub"
        #psk="OctocatsRule!"
        psk=79f529240a2ec5222e11a1e2d077c2c9c8b1257cc06024b58fd9a0e74c713e1e
}
EOF

cat<<EOF > /media/etc/network/interfaces
auto lo wlan0

iface lo inet loopback

iface eth0 inet dhcp

allow-hotplug wlan0
iface wlan0 inet dhcp
pre-up wpa_supplicant -Dwext -i wlan0 -c /boot/wpa_supplicant.conf -B
post-down killall -q wpa_supplicant
EOF


if [ ! -d /media/root/.ssh ]; then
   mkdir -p /media/root/.ssh
fi
cat<<EOF > /media/root/.ssh/authorized_keys
sh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDLuHahxjD7lAWGpE1LLFXenj+90WcMBzZNdw1OuCqOR9ioJag/atjKRuV7e/SiZ2ITtArjsz/YRCsgdaB34YTovFVf5U59uGuiawfa2zpTk8TmojvpcNqNOll4kM6Fa280Uu89cy8aCANhPnnZC4l9YBuuemCDllFPvcUTkN5GpIr0eWEsI+ZbCW4jDsLsZHCFMJ0MbeRfJR1wqid+AgB3xeEIJulpqinWkx3IyGHDnG//A4AglXw7ndz0gxEeE1JAtvVX20CgZPFdRk4UivU8MtLffAh5G/gCYsDjKXHaZaswpvQAf3BcI1WuBqfA2KwP2GJLw93wmbb0euWCwJfYUobeedjxWUzscYzY5yCadPZla+FGEPCbTeRK525OxgRkxXRzW2Tlidba8wKI0xMJ66ZqizRV4wBJvEZDOI+s+kAuPEHR7RIHmagfEUUHQQFKOFxIsfBYnA5Bo12HVopEkbImQTJrAu0mwwChZD+TgOtfRLs35Cgn5uBbHGU+DKt47uMN/ZTWL/CaFX+mDv3fB1W3bB1b3g6GxpttHBtESddNXeeMY5TfT8ffMj/uOQ2aZWOwqFIlDqtvbuNxLCpjGGJKM0FFZMVq9JQ01aEF98oNNv0cwJ5fUNijndF3n7D1sfEo4mt/Fe2Ni7muusWAAjMs6BCP9cHRKj+Lgio/Yw== jameswhite@forseti.local
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDt1d4yn+Ka1a5BrnwJ8QI0SiuxLSyH2RfctoPGWZzlxElm0L22DnEj3spMpR8m4K6ErUFz8ICRHyJ+0bj3KqeFUfVc1EVZbaY6B9/QdaSSm9KZM5Pew+SMoH4lvAV0BSX5DcHwln83rjKP5/fTnNw28OwvJ5MCd0GS2y/7mTXsWdH+dARYF6gmQQfwJ+cVnjNUxJlQtZY6I0XniDy7ZYrWLecYx409NlQBdI5ZLtFW4SLbDKarHVg4wf82qjc9xvErMLRLrgQ6LIkdCK8HQq506C26fEF2PHEkgMboelNwi8aagGx4Ce0zFq3xO45pxQqR/9J+RVI1anZX0tIm20ul jameswhite@Jamess-MacBook-Pro.local
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC8mR/RY6xbuIwauXTaqQk83jBE5cRUF8Ulc5hw7han6QvSV67ju7UhFSAt4eDZKXc/5uR1fkoTiyLBGakknWDfdysv++HASraCPd24wwe0XzqKW3UdQh3nzbzATSOp/W77MxWqLfWrGormZMp/FzsCw0G85rMAZN8crc5Jg3QAAgsGEoIMgNh7j2l+qH1ciw3gUS6kuSOqXxlWTY2ztEv3QaR/3faitsWUuN1IL5iEBFaSazqYcPXqe7NV5W8kgKgyaEZX2PfZ+MMPOLy6q2bqUJxSDR58t/ljQRzSEd12bjJgkyjoRE5SwlNkJF3Ayt1UO69GjJTjanlp1p6DAATDNRuMwq6y4ytA6zGOkrd+zhBFfvQpcrKt6SPxPbtXodJgI3uHABr1vQhSDt4dfsmMUZc6zdmd1/juYub7VUNjboPA+Kf8NfS+LYeidYfSZs2i7yUcHdogNfGNIjeKjNhI8pmoLPmKhSzdjY4FbMDlDbx7n/LQfGgAXbhK5ctln9l1vVaTpyY35cwBiKI3q4v7HluUt0faZGIZbwS0ODjHfJ9s5i7+4jvV/R0DLh9r74SPLgYLvkVwhxgmi2MYHKAYn60/cEjMzTrqczm8TP50M0h/l8WunZ0b6i31OV/1PVdcK00CrLrk5kmt2EGkZUDHeTOXaaoKvbbQCdIvQnKpVw== jameswhite@aegir.local
EOF

chown -R root:root /media/root/.ssh
chmod -R 750 /media/root/.ssh

if [ ! -d /media/home/pi/.ssh ]; then
   mkdir -p /media/home/pi/.ssh
fi
cat<<EOF > /media/home/pi/.ssh/authorized_keys
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDLuHahxjD7lAWGpE1LLFXenj+90WcMBzZNdw1OuCqOR9ioJag/atjKRuV7e/SiZ2ITtArjsz/YRCsgdaB34YTovFVf5U59uGuiawfa2zpTk8TmojvpcNqNOll4kM6Fa280Uu89cy8aCANhPnnZC4l9YBuuemCDllFPvcUTkN5GpIr0eWEsI+ZbCW4jDsLsZHCFMJ0MbeRfJR1wqid+AgB3xeEIJulpqinWkx3IyGHDnG//A4AglXw7ndz0gxEeE1JAtvVX20CgZPFdRk4UivU8MtLffAh5G/gCYsDjKXHaZaswpvQAf3BcI1WuBqfA2KwP2GJLw93wmbb0euWCwJfYUobeedjxWUzscYzY5yCadPZla+FGEPCbTeRK525OxgRkxXRzW2Tlidba8wKI0xMJ66ZqizRV4wBJvEZDOI+s+kAuPEHR7RIHmagfEUUHQQFKOFxIsfBYnA5Bo12HVopEkbImQTJrAu0mwwChZD+TgOtfRLs35Cgn5uBbHGU+DKt47uMN/ZTWL/CaFX+mDv3fB1W3bB1b3g6GxpttHBtESddNXeeMY5TfT8ffMj/uOQ2aZWOwqFIlDqtvbuNxLCpjGGJKM0FFZMVq9JQ01aEF98oNNv0cwJ5fUNijndF3n7D1sfEo4mt/Fe2Ni7muusWAAjMs6BCP9cHRKj+Lgio/Yw== jameswhite@forseti.local
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDt1d4yn+Ka1a5BrnwJ8QI0SiuxLSyH2RfctoPGWZzlxElm0L22DnEj3spMpR8m4K6ErUFz8ICRHyJ+0bj3KqeFUfVc1EVZbaY6B9/QdaSSm9KZM5Pew+SMoH4lvAV0BSX5DcHwln83rjKP5/fTnNw28OwvJ5MCd0GS2y/7mTXsWdH+dARYF6gmQQfwJ+cVnjNUxJlQtZY6I0XniDy7ZYrWLecYx409NlQBdI5ZLtFW4SLbDKarHVg4wf82qjc9xvErMLRLrgQ6LIkdCK8HQq506C26fEF2PHEkgMboelNwi8aagGx4Ce0zFq3xO45pxQqR/9J+RVI1anZX0tIm20ul jameswhite@Jamess-MacBook-Pro.local
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC8mR/RY6xbuIwauXTaqQk83jBE5cRUF8Ulc5hw7han6QvSV67ju7UhFSAt4eDZKXc/5uR1fkoTiyLBGakknWDfdysv++HASraCPd24wwe0XzqKW3UdQh3nzbzATSOp/W77MxWqLfWrGormZMp/FzsCw0G85rMAZN8crc5Jg3QAAgsGEoIMgNh7j2l+qH1ciw3gUS6kuSOqXxlWTY2ztEv3QaR/3faitsWUuN1IL5iEBFaSazqYcPXqe7NV5W8kgKgyaEZX2PfZ+MMPOLy6q2bqUJxSDR58t/ljQRzSEd12bjJgkyjoRE5SwlNkJF3Ayt1UO69GjJTjanlp1p6DAATDNRuMwq6y4ytA6zGOkrd+zhBFfvQpcrKt6SPxPbtXodJgI3uHABr1vQhSDt4dfsmMUZc6zdmd1/juYub7VUNjboPA+Kf8NfS+LYeidYfSZs2i7yUcHdogNfGNIjeKjNhI8pmoLPmKhSzdjY4FbMDlDbx7n/LQfGgAXbhK5ctln9l1vVaTpyY35cwBiKI3q4v7HluUt0faZGIZbwS0ODjHfJ9s5i7+4jvV/R0DLh9r74SPLgYLvkVwhxgmi2MYHKAYn60/cEjMzTrqczm8TP50M0h/l8WunZ0b6i31OV/1PVdcK00CrLrk5kmt2EGkZUDHeTOXaaoKvbbQCdIvQnKpVw== jameswhite@aegir.local
EOF

chown -R 1000:1000 /media/home/pi/.ssh
chmod -R 750 /media/home/pi/.ssh

# grep "^1:2345:respawn:/bin/login" /media/etc/inittab && sed -ie 's/\(^1:2345:respawn:\/bin\/login\)/#&/' /media/etc/inittab
# grep "^#1:2345:respawn:\/sbin\/getty" /media/etc/inittab && sed -ie 's/^#\(1:2345:respawn:\/sbin\/getty\)/\1/' /media/etc/inittab

# sed -i -e 's/xserver-allow-tcp=false/xserver-allow-tcp=true/' /media/etc/lightdm/lightdm.conf
# sleep 2

mount | grep mmcblk0p1 &&  umount /media/boot/
mount | grep mmcblk0p2 &&  umount /media/

